# Generated by Django 5.2.16 on 2026-07-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_role_is_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='core', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('welcome_admin', 'Welcome — New Org Admin'), ('access_request_submitted', 'Access Request Submitted'), ('access_request_accepted', 'Access Request Accepted'), ('certificate_issued', 'Certificate Issued'), ('billing_reminder', 'Billing Reminder'), ('password_reset', 'Password Reset')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='Use {{ variable }} placeholders, e.g. {{ user_name }}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='LMS Platform', max_length=150)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('favicon_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#4f46e5', max_length=7)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('terms_url', models.URLField(blank=True, default='')),
                ('privacy_url', models.URLField(blank=True, default='')),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('password_min_length', models.IntegerField(default=8)),
                ('session_timeout_minutes', models.IntegerField(default=480)),
                ('max_upload_size_mb', models.IntegerField(default=500)),
                ('activity_log_retention_days', models.IntegerField(default=365)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_departments', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_create_courses', models.BooleanField(default=False)),
                ('can_edit_courses', models.BooleanField(default=False)),
                ('can_publish_courses', models.BooleanField(default=False)),
                ('can_manage_module_access', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_certificates', models.BooleanField(default=False)),
                ('is_org_admin_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('max_courses', models.IntegerField(blank=True, null=True)),
                ('max_sites', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('included_features', models.ManyToManyField(blank=True, related_name='included_in_plans', to='master_setup.feature')),
            ],
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('lookup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='master_setup.lookuptype')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('lookup_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SiteFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_access', to='master_setup.feature')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='organizations.site')),
            ],
            options={
                'unique_together': {('site', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='TerminologyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_term', models.CharField(max_length=100)),
                ('custom_term', models.CharField(max_length=100)),
                ('custom_term_plural', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminologies', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'standard_term')},
            },
        ),
    ]
