# Generated by Django 5.2.16 on 2026-07-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(max_length=255)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_setup.feature')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='master_setup.navitem')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='master_setup.workspace')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('component_key', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_setup.feature')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='master_setup.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='roleblueprint',
            name='workspaces',
            field=models.ManyToManyField(related_name='roles', to='master_setup.workspace'),
        ),
    ]
