# Generated by Django 5.2.16 on 2026-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_workspace_navitem_dashboardwidget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleblueprint',
            name='workspaces',
            field=models.ManyToManyField(related_name='role_blueprints', to='master_setup.workspace'),
        ),
    ]
