# Generated by Django 5.2.16 on 2026-07-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0004_alter_roleblueprint_workspaces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleBlueprint',
        ),
    ]
