# Generated by Django 5.2.16 on 2026-07-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0005_delete_roleblueprint'),
        ('organizations', '0013_organization_subdomain_routing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='allowed_ip_range',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_system_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='from_email',
            field=models.EmailField(blank=True, default='noreply@halyardlearn.com', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='Halyard Learn', max_length=150),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='primary_color',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(blank=True, default='support@halyardlearn.com', max_length=254),
        ),
        migrations.CreateModel(
            name='OrganizationFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_access', to='master_setup.feature')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'feature')},
            },
        ),
    ]
