# Generated by Django 5.2.16 on 2026-07-29 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0006_platformsettings_allowed_ip_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolkitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('icon', models.CharField(default='BookOpen', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'toolkit_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('module_name', models.CharField(max_length=150)),
                ('feature_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('files_modified', models.JSONField(blank=True, default=list)),
                ('developer_name', models.CharField(default='System Core', max_length=150)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('deprecated', 'Deprecated')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'toolkit_changelog',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('new_features', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('bug_fixes', models.JSONField(blank=True, default=list)),
                ('breaking_changes', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'toolkit_releasenote',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_article_ids', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('ai_embeddings_index', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_toolkit_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='master_setup.toolkitcategory')),
            ],
            options={
                'db_table': 'toolkit_article',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='master_setup.toolkitarticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toolkit_article_version',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='toolkit_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='master_setup.toolkitarticle')),
            ],
            options={
                'db_table': 'toolkit_attachment',
            },
        ),
        migrations.CreateModel(
            name='ToolkitAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('article_title', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=150)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toolkit_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='toolkit_backups/')),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toolkit_backup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolkitDependencyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('affected_models', models.JSONField(blank=True, default=list)),
                ('affected_apis', models.JSONField(blank=True, default=list)),
                ('affected_components', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='master_setup.toolkitdependencynode')),
            ],
            options={
                'db_table': 'toolkit_dependencynode',
            },
        ),
        migrations.CreateModel(
            name='ToolkitBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='master_setup.toolkitarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toolkit_bookmark',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ToolkitRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='master_setup.toolkitarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolkit_recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'toolkit_recently_viewed',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
