# Generated by Django 5.2.16 on 2026-07-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='ai_agents',
            new_name='admin_console',
        ),
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='attendance',
            new_name='ai_assistant',
        ),
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='calendar_meetings',
            new_name='certifications',
        ),
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='company_pulse',
            new_name='content_authoring',
        ),
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='custom_boards',
            new_name='course_catalog',
        ),
        migrations.RenameField(
            model_name='moduleaccess',
            old_name='directory',
            new_name='learning_paths',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='docs_notes',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='hr_requests',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='knowledge_base',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='minutes_of_meeting',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='my_day',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='policies',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='predictive_insights',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='recognition',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='resource_planning',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='team_chat',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='template_marketplace',
        ),
        migrations.RemoveField(
            model_name='moduleaccess',
            name='workflow_automation',
        ),
    ]
