# Generated by Django 5.2.16 on 2026-07-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_department_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Completion Certificate', max_length=255)),
                ('body_html', models.TextField(default='<h1>Certificate of Completion</h1><p>Awarded to {{ user.full_name }}</p>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='organizations.organization')),
            ],
        ),
    ]
