# Generated by Django 5.2.16 on 2026-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='next_payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='plan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, help_text='Public URL for this site instance', null=True),
        ),
        migrations.AlterField(
            model_name='billingconfiguration',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
