# Generated by Django 5.2.16 on 2026-07-16 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_billingconfiguration_next_payment_due_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('login', 'Logged in'), ('logout', 'Logged out'), ('login_failed', 'Failed login attempt'), ('org_created', 'Organization created'), ('org_updated', 'Organization updated'), ('org_deleted', 'Organization deleted'), ('site_created', 'Site created'), ('site_updated', 'Site updated'), ('site_deleted', 'Site deleted'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deactivated', 'User deactivated'), ('role_created', 'Role created'), ('role_updated', 'Role updated'), ('role_deleted', 'Role deleted'), ('course_created', 'Course created'), ('course_published', 'Course published'), ('course_updated', 'Course updated'), ('lesson_video_uploaded', 'Lesson video uploaded'), ('assessment_imported', 'Assessment questions imported'), ('billing_updated', 'Billing configuration updated'), ('billing_status_changed', 'Billing status changed'), ('module_access_changed', 'Module access changed'), ('course_completed', 'Course completed'), ('assessment_attempted', 'Assessment attempt submitted'), ('certificate_issued', 'Certificate issued')], max_length=50)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='organizatio_organiz_e3ecbe_idx'), models.Index(fields=['actor', '-created_at'], name='organizatio_actor_i_3b6b43_idx'), models.Index(fields=['action', '-created_at'], name='organizatio_action_fb5b5b_idx')],
            },
        ),
    ]
