# Generated by Django 5.2.16 on 2026-07-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin_role',
            field=models.BooleanField(default=False),
        ),
    ]
