# Generated by Django 5.2.16 on 2026-07-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0001_initial'),
        ('organizations', '0008_migrate_master_setup_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingconfiguration',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='billingconfiguration',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='master_setup.plan'),
        ),
        migrations.DeleteModel(
            name='ModuleAccess',
        ),
    ]
