# Generated by Django 5.2.16 on 2026-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_billingconfiguration_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('6_months', '6 Months'), ('1_year', '1 Year'), ('custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='compliance_badges',
            field=models.JSONField(blank=True, default=list, help_text="This organization's own trust badges, independent of the platform's. Only true, verified claims."),
        ),
        migrations.AddField(
            model_name='organization',
            name='login_hero_description',
            field=models.TextField(blank=True, default='', help_text='Optional longer paragraph under the tagline. Left blank = not shown, not a placeholder.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='login_welcome_message',
            field=models.CharField(blank=True, default='', help_text='Heading above the login form for this org\'s employees, e.g. "Welcome to Halyard Learn". Blank = falls back to platform default at render time, not stored as a duplicate default here.', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text="This organization's logo, shown on their branded login page and elsewhere their identity appears."),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, default='', help_text='Hex color, e.g. #1E40AF. Used for the login hero panel background and accent elements.', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short headline on this organization\'s login page, e.g. "Excellence in patient care."', max_length=255),
        ),
    ]
