# Generated by Django 5.2.16 on 2026-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_billingconfiguration_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sub_domain',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
