# Generated by Django 5.2.16 on 2026-07-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setup', '0003_workspace_navitem_dashboardwidget_and_more'),
        ('organizations', '0011_alter_organization_sub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='workspaces',
            field=models.ManyToManyField(related_name='roles', to='master_setup.workspace'),
        ),
    ]
