# Generated by Django 5.2.16 on 2026-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_role_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subdomain_routing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
