# Generated by Django 5.2.16 on 2026-07-28 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_issuedcertificate_template_and_more'),
        ('organizations', '0013_organization_subdomain_routing_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='import_scratch/')),
                ('source_format', models.CharField(choices=[('pdf', 'PDF Document'), ('pptx', 'PowerPoint Presentation'), ('docx', 'Word Document'), ('video', 'Video File'), ('audio', 'Audio File'), ('html', 'HTML Package'), ('zip', 'ZIP Archive'), ('scorm', 'SCORM Package')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('parsing', 'Parsing'), ('converting', 'Converting'), ('normalizing', 'Normalizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='organizations.organization')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='courses.course')),
            ],
            options={
                'db_table': 'import_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
