# Generated by Django 5.2.16 on 2026-07-28 09:45

import authoring_engine.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_issuedcertificate_template_and_more'),
        ('organizations', '0013_organization_subdomain_routing_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to=authoring_engine.models.org_asset_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoring_assets', to='organizations.organization')),
            ],
            options={
                'db_table': 'authoring_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('manifest_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_versions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_versions', to='organizations.organization')),
            ],
            options={
                'db_table': 'authoring_courseversion',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('video', 'Video'), ('image', 'Image'), ('audio', 'Audio'), ('table', 'Table'), ('quote', 'Quote'), ('code', 'Code'), ('callout', 'Callout'), ('pdf', 'PDF'), ('interaction', 'Interaction'), ('quiz', 'Quiz'), ('scenario', 'Scenario')], max_length=50)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to='organizations.organization')),
                ('parent_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authoring_engine.lessonblock')),
            ],
            options={
                'db_table': 'authoring_lessonblock',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_select', 'Multiple Select'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('short_answer', 'Short Answer')], max_length=30)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_feedback', models.TextField(blank=True, default='')),
                ('incorrect_feedback', models.TextField(blank=True, default='')),
                ('hint', models.TextField(blank=True, default='')),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kc_questions', to='organizations.organization')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kc_questions', to='authoring_engine.lessonblock')),
            ],
            options={
                'db_table': 'authoring_kc_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteractionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('tabs', 'Tabs'), ('accordion', 'Accordion'), ('timeline', 'Timeline'), ('flashcards', 'Flashcards'), ('hotspots', 'Hotspots'), ('image_compare', 'Image Compare'), ('before_after', 'Before-After'), ('clickable_cards', 'Clickable Cards'), ('process_flow', 'Process Flow'), ('drag_drop', 'Drag & Drop'), ('sorting', 'Sorting'), ('matching', 'Matching'), ('slider', 'Slider'), ('image_reveal', 'Image Reveal'), ('layered_content', 'Layered Content')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_payload', to='authoring_engine.lessonblock')),
            ],
            options={
                'db_table': 'authoring_interactionblock',
            },
        ),
        migrations.CreateModel(
            name='LessonBlockTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_block_ids', models.JSONField(blank=True, default=list)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='block_tree', to='courses.lesson')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_trees', to='organizations.organization')),
            ],
            options={
                'db_table': 'authoring_lessonblocktree',
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='authoring_engine.lessonblocktree'),
        ),
        migrations.CreateModel(
            name='ReadingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, default='')),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_payload', to='authoring_engine.lessonblock')),
            ],
            options={
                'db_table': 'authoring_readingcontent',
            },
        ),
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('media_url', models.CharField(blank=True, default='', max_length=1000)),
                ('is_start_node', models.BooleanField(default=False)),
                ('is_ending_node', models.BooleanField(default=False)),
                ('ending_type', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('neutral', 'Neutral')], max_length=30, null=True)),
                ('score_delta', models.IntegerField(default=0)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_nodes', to='authoring_engine.lessonblock')),
            ],
            options={
                'db_table': 'authoring_scenarionode',
            },
        ),
    ]
