# Generated by Django 5.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('category', models.CharField(
                    choices=[('Oncology', 'Oncology'), ('Sterilization', 'Sterilization'), ('Compliance', 'Compliance')],
                    default='Oncology', max_length=50,
                )),
                ('hero_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration_hrs', models.FloatField(default=1.0)),
                ('passing_score', models.IntegerField(default=80)),
                ('level', models.CharField(
                    choices=[('Foundational', 'Foundational'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')],
                    default='Foundational', max_length=50,
                )),
                ('status', models.CharField(
                    choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')],
                    default='draft', max_length=20,
                )),
                ('accent', models.CharField(default='var(--brand)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='modules',
                    to='courses.course',
                )),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(default='5 min', max_length=50)),
                ('type', models.CharField(
                    choices=[
                        ('video', 'Video'), ('interactive', 'Interactive'), ('reading', 'Reading'),
                        ('knowledge_check', 'Knowledge Check'), ('scenario', 'Scenario'),
                    ],
                    default='video', max_length=20,
                )),
                ('order', models.IntegerField(default=0)),
                ('video_id', models.IntegerField(
                    blank=True, null=True,
                    help_text='Maps to VIDEO_MAP index in urls.py',
                )),
                ('interaction', models.CharField(
                    blank=True,
                    choices=[
                        ('cell_explorer', 'Cell Explorer'),
                        ('comparison', 'Normal vs Cancer Comparison'),
                        ('metastasis_animation', 'Metastasis Animation'),
                        ('branching_scenario', 'Branching Scenario'),
                        ('drag_drop_match', 'Drag & Drop Match'),
                        ('reveal_cards', 'Reveal Cards'),
                        ('knowledge_check', 'Knowledge Check'),
                    ],
                    help_text='Interaction component slug, used when type is interactive/scenario/knowledge_check',
                    max_length=50, null=True,
                )),
                ('module', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lessons',
                    to='courses.module',
                )),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
