# Generated by Django 5.2.16 on 2026-07-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_video_url_assessmentquestion'),
        ('organizations', '0003_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organizations.organization'),
        ),
    ]
