# Generated by Django 5.2.16 on 2026-07-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_organization'),
        ('organizations', '0004_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='organizations.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='time_limit_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
