# Generated by Django 5.2.16 on 2026-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assessmentattempt_lessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
    ]
