# Generated by Django 5.2.16 on 2026-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hero_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='Direct URL to the uploaded video', max_length=1000, null=True),
        ),
    ]
