# Generated by Django 5.2.16 on 2026-07-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_author_accessrequest_issuedcertificate'),
        ('organizations', '0011_alter_organization_sub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge_icon',
            field=models.CharField(blank=True, default='🎓', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='badge_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='courses.learningpath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
    ]
