# Generated by Django 5.2.16 on 2026-07-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_scorm_support'),
        ('organizations', '0013_organization_subdomain_routing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedcertificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='organizations.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='template_html_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
