# Generated by Django 5.2.16 on 2026-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_issuedcertificate_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='interaction',
            field=models.CharField(blank=True, help_text='[Deprecated] Legacy interaction component slug', max_length=50, null=True),
        ),
    ]
