# Generated by Django 5.2.16 on 2026-08-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lesson_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accent',
            field=models.CharField(blank=True, default='var(--brand)', max_length=100),
        ),
    ]
