/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PendingRegistrationRouteImport } from './routes/pending-registration'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as OrgAdminRouteImport } from './routes/org-admin'
import { Route as MessengerRouteImport } from './routes/messenger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthoringRouteImport } from './routes/authoring'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgAdminIndexRouteImport } from './routes/org-admin.index'
import { Route as SuperAdminToolkitRouteImport } from './routes/super-admin.toolkit'
import { Route as SuperAdminSitesRouteImport } from './routes/super-admin.sites'
import { Route as SuperAdminSetupGuideRouteImport } from './routes/super-admin.setup-guide'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminPlansRouteImport } from './routes/super-admin.plans'
import { Route as SuperAdminOrganizationsRouteImport } from './routes/super-admin.organizations'
import { Route as SuperAdminFeatureRegistryRouteImport } from './routes/super-admin.feature-registry'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SuperAdminBillingRouteImport } from './routes/super-admin.billing'
import { Route as SuperAdminActivityRouteImport } from './routes/super-admin.activity'
import { Route as OrgAdminUsersRouteImport } from './routes/org-admin.users'
import { Route as OrgAdminRolesRouteImport } from './routes/org-admin.roles'
import { Route as OrgAdminModuleAccessRouteImport } from './routes/org-admin.module-access'
import { Route as OrgAdminDepartmentsRouteImport } from './routes/org-admin.departments'
import { Route as OrgAdminCoursesRouteImport } from './routes/org-admin.courses'
import { Route as OrgAdminCertificatesRouteImport } from './routes/org-admin.certificates'
import { Route as OrgAdminActivityRouteImport } from './routes/org-admin.activity'
import { Route as LoginOrgSlugRouteImport } from './routes/login.$orgSlug'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CertificatesCertIdRouteImport } from './routes/certificates.$certId'
import { Route as SuperAdminSitesAddRouteImport } from './routes/super-admin.sites_.add'
import { Route as SuperAdminSitesSiteIdRouteImport } from './routes/super-admin.sites_.$siteId'
import { Route as SuperAdminOrganizationsAddRouteImport } from './routes/super-admin.organizations_.add'
import { Route as SuperAdminOrganizationsOrgIdRouteImport } from './routes/super-admin.organizations_.$orgId'
import { Route as CoursesCourseIdAssessmentRouteImport } from './routes/courses.$courseId.assessment'
import { Route as SuperAdminSitesSiteIdEditRouteImport } from './routes/super-admin.sites_.$siteId_.edit'
import { Route as SuperAdminOrganizationsOrgIdEditRouteImport } from './routes/super-admin.organizations_.$orgId_.edit'
import { Route as OrgAdminCoursesCourseIdPreviewRouteImport } from './routes/org-admin.courses.$courseId.preview'
import { Route as OrgAdminCoursesCourseIdBuilderRouteImport } from './routes/org-admin.courses.$courseId.builder'
import { Route as CoursesCourseIdPlayLessonIdRouteImport } from './routes/courses.$courseId.play.$lessonId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRegistrationRoute = PendingRegistrationRouteImport.update({
  id: '/pending-registration',
  path: '/pending-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAdminRoute = OrgAdminRouteImport.update({
  id: '/org-admin',
  path: '/org-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MessengerRoute = MessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoringRoute = AuthoringRouteImport.update({
  id: '/authoring',
  path: '/authoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAdminIndexRoute = OrgAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgAdminRoute,
} as any)
const SuperAdminToolkitRoute = SuperAdminToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSitesRoute = SuperAdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSetupGuideRoute = SuperAdminSetupGuideRouteImport.update({
  id: '/setup-guide',
  path: '/setup-guide',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlansRoute = SuperAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOrganizationsRoute = SuperAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminFeatureRegistryRoute =
  SuperAdminFeatureRegistryRouteImport.update({
    id: '/feature-registry',
    path: '/feature-registry',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBillingRoute = SuperAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminActivityRoute = SuperAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperAdminRoute,
} as any)
const OrgAdminUsersRoute = OrgAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminRolesRoute = OrgAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminModuleAccessRoute = OrgAdminModuleAccessRouteImport.update({
  id: '/module-access',
  path: '/module-access',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminDepartmentsRoute = OrgAdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminCoursesRoute = OrgAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminCertificatesRoute = OrgAdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminActivityRoute = OrgAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OrgAdminRoute,
} as any)
const LoginOrgSlugRoute = LoginOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => LoginRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertIdRoute = CertificatesCertIdRouteImport.update({
  id: '/$certId',
  path: '/$certId',
  getParentRoute: () => CertificatesRoute,
} as any)
const SuperAdminSitesAddRoute = SuperAdminSitesAddRouteImport.update({
  id: '/sites_/add',
  path: '/sites/add',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSitesSiteIdRoute = SuperAdminSitesSiteIdRouteImport.update({
  id: '/sites_/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOrganizationsAddRoute =
  SuperAdminOrganizationsAddRouteImport.update({
    id: '/organizations_/add',
    path: '/organizations/add',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminOrganizationsOrgIdRoute =
  SuperAdminOrganizationsOrgIdRouteImport.update({
    id: '/organizations_/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const CoursesCourseIdAssessmentRoute =
  CoursesCourseIdAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const SuperAdminSitesSiteIdEditRoute =
  SuperAdminSitesSiteIdEditRouteImport.update({
    id: '/sites_/$siteId_/edit',
    path: '/sites/$siteId/edit',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminOrganizationsOrgIdEditRoute =
  SuperAdminOrganizationsOrgIdEditRouteImport.update({
    id: '/organizations_/$orgId_/edit',
    path: '/organizations/$orgId/edit',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const OrgAdminCoursesCourseIdPreviewRoute =
  OrgAdminCoursesCourseIdPreviewRouteImport.update({
    id: '/$courseId/preview',
    path: '/$courseId/preview',
    getParentRoute: () => OrgAdminCoursesRoute,
  } as any)
const OrgAdminCoursesCourseIdBuilderRoute =
  OrgAdminCoursesCourseIdBuilderRouteImport.update({
    id: '/$courseId/builder',
    path: '/$courseId/builder',
    getParentRoute: () => OrgAdminCoursesRoute,
  } as any)
const CoursesCourseIdPlayLessonIdRoute =
  CoursesCourseIdPlayLessonIdRouteImport.update({
    id: '/play/$lessonId',
    path: '/play/$lessonId',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/authoring': typeof AuthoringRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/messenger': typeof MessengerRoute
  '/org-admin': typeof OrgAdminRouteWithChildren
  '/paths': typeof PathsRoute
  '/pending-registration': typeof PendingRegistrationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/users': typeof UsersRoute
  '/certificates/$certId': typeof CertificatesCertIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/login/$orgSlug': typeof LoginOrgSlugRoute
  '/org-admin/activity': typeof OrgAdminActivityRoute
  '/org-admin/certificates': typeof OrgAdminCertificatesRoute
  '/org-admin/courses': typeof OrgAdminCoursesRouteWithChildren
  '/org-admin/departments': typeof OrgAdminDepartmentsRoute
  '/org-admin/module-access': typeof OrgAdminModuleAccessRoute
  '/org-admin/roles': typeof OrgAdminRolesRoute
  '/org-admin/users': typeof OrgAdminUsersRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/feature-registry': typeof SuperAdminFeatureRegistryRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/setup-guide': typeof SuperAdminSetupGuideRoute
  '/super-admin/sites': typeof SuperAdminSitesRoute
  '/super-admin/toolkit': typeof SuperAdminToolkitRoute
  '/org-admin/': typeof OrgAdminIndexRoute
  '/courses/$courseId/assessment': typeof CoursesCourseIdAssessmentRoute
  '/super-admin/organizations/$orgId': typeof SuperAdminOrganizationsOrgIdRoute
  '/super-admin/organizations/add': typeof SuperAdminOrganizationsAddRoute
  '/super-admin/sites/$siteId': typeof SuperAdminSitesSiteIdRoute
  '/super-admin/sites/add': typeof SuperAdminSitesAddRoute
  '/courses/$courseId/play/$lessonId': typeof CoursesCourseIdPlayLessonIdRoute
  '/org-admin/courses/$courseId/builder': typeof OrgAdminCoursesCourseIdBuilderRoute
  '/org-admin/courses/$courseId/preview': typeof OrgAdminCoursesCourseIdPreviewRoute
  '/super-admin/organizations/$orgId/edit': typeof SuperAdminOrganizationsOrgIdEditRoute
  '/super-admin/sites/$siteId/edit': typeof SuperAdminSitesSiteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/authoring': typeof AuthoringRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/messenger': typeof MessengerRoute
  '/paths': typeof PathsRoute
  '/pending-registration': typeof PendingRegistrationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/users': typeof UsersRoute
  '/certificates/$certId': typeof CertificatesCertIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/login/$orgSlug': typeof LoginOrgSlugRoute
  '/org-admin/activity': typeof OrgAdminActivityRoute
  '/org-admin/certificates': typeof OrgAdminCertificatesRoute
  '/org-admin/courses': typeof OrgAdminCoursesRouteWithChildren
  '/org-admin/departments': typeof OrgAdminDepartmentsRoute
  '/org-admin/module-access': typeof OrgAdminModuleAccessRoute
  '/org-admin/roles': typeof OrgAdminRolesRoute
  '/org-admin/users': typeof OrgAdminUsersRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/feature-registry': typeof SuperAdminFeatureRegistryRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/setup-guide': typeof SuperAdminSetupGuideRoute
  '/super-admin/sites': typeof SuperAdminSitesRoute
  '/super-admin/toolkit': typeof SuperAdminToolkitRoute
  '/org-admin': typeof OrgAdminIndexRoute
  '/courses/$courseId/assessment': typeof CoursesCourseIdAssessmentRoute
  '/super-admin/organizations/$orgId': typeof SuperAdminOrganizationsOrgIdRoute
  '/super-admin/organizations/add': typeof SuperAdminOrganizationsAddRoute
  '/super-admin/sites/$siteId': typeof SuperAdminSitesSiteIdRoute
  '/super-admin/sites/add': typeof SuperAdminSitesAddRoute
  '/courses/$courseId/play/$lessonId': typeof CoursesCourseIdPlayLessonIdRoute
  '/org-admin/courses/$courseId/builder': typeof OrgAdminCoursesCourseIdBuilderRoute
  '/org-admin/courses/$courseId/preview': typeof OrgAdminCoursesCourseIdPreviewRoute
  '/super-admin/organizations/$orgId/edit': typeof SuperAdminOrganizationsOrgIdEditRoute
  '/super-admin/sites/$siteId/edit': typeof SuperAdminSitesSiteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/authoring': typeof AuthoringRoute
  '/catalog': typeof CatalogRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRouteWithChildren
  '/messenger': typeof MessengerRoute
  '/org-admin': typeof OrgAdminRouteWithChildren
  '/paths': typeof PathsRoute
  '/pending-registration': typeof PendingRegistrationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/users': typeof UsersRoute
  '/certificates/$certId': typeof CertificatesCertIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/login/$orgSlug': typeof LoginOrgSlugRoute
  '/org-admin/activity': typeof OrgAdminActivityRoute
  '/org-admin/certificates': typeof OrgAdminCertificatesRoute
  '/org-admin/courses': typeof OrgAdminCoursesRouteWithChildren
  '/org-admin/departments': typeof OrgAdminDepartmentsRoute
  '/org-admin/module-access': typeof OrgAdminModuleAccessRoute
  '/org-admin/roles': typeof OrgAdminRolesRoute
  '/org-admin/users': typeof OrgAdminUsersRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/feature-registry': typeof SuperAdminFeatureRegistryRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/setup-guide': typeof SuperAdminSetupGuideRoute
  '/super-admin/sites': typeof SuperAdminSitesRoute
  '/super-admin/toolkit': typeof SuperAdminToolkitRoute
  '/org-admin/': typeof OrgAdminIndexRoute
  '/courses/$courseId/assessment': typeof CoursesCourseIdAssessmentRoute
  '/super-admin/organizations_/$orgId': typeof SuperAdminOrganizationsOrgIdRoute
  '/super-admin/organizations_/add': typeof SuperAdminOrganizationsAddRoute
  '/super-admin/sites_/$siteId': typeof SuperAdminSitesSiteIdRoute
  '/super-admin/sites_/add': typeof SuperAdminSitesAddRoute
  '/courses/$courseId/play/$lessonId': typeof CoursesCourseIdPlayLessonIdRoute
  '/org-admin/courses/$courseId/builder': typeof OrgAdminCoursesCourseIdBuilderRoute
  '/org-admin/courses/$courseId/preview': typeof OrgAdminCoursesCourseIdPreviewRoute
  '/super-admin/organizations_/$orgId_/edit': typeof SuperAdminOrganizationsOrgIdEditRoute
  '/super-admin/sites_/$siteId_/edit': typeof SuperAdminSitesSiteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/authoring'
    | '/catalog'
    | '/certificates'
    | '/dashboard'
    | '/login'
    | '/messenger'
    | '/org-admin'
    | '/paths'
    | '/pending-registration'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/users'
    | '/certificates/$certId'
    | '/courses/$courseId'
    | '/login/$orgSlug'
    | '/org-admin/activity'
    | '/org-admin/certificates'
    | '/org-admin/courses'
    | '/org-admin/departments'
    | '/org-admin/module-access'
    | '/org-admin/roles'
    | '/org-admin/users'
    | '/super-admin/activity'
    | '/super-admin/billing'
    | '/super-admin/dashboard'
    | '/super-admin/feature-registry'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/setup-guide'
    | '/super-admin/sites'
    | '/super-admin/toolkit'
    | '/org-admin/'
    | '/courses/$courseId/assessment'
    | '/super-admin/organizations/$orgId'
    | '/super-admin/organizations/add'
    | '/super-admin/sites/$siteId'
    | '/super-admin/sites/add'
    | '/courses/$courseId/play/$lessonId'
    | '/org-admin/courses/$courseId/builder'
    | '/org-admin/courses/$courseId/preview'
    | '/super-admin/organizations/$orgId/edit'
    | '/super-admin/sites/$siteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/authoring'
    | '/catalog'
    | '/certificates'
    | '/dashboard'
    | '/login'
    | '/messenger'
    | '/paths'
    | '/pending-registration'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/users'
    | '/certificates/$certId'
    | '/courses/$courseId'
    | '/login/$orgSlug'
    | '/org-admin/activity'
    | '/org-admin/certificates'
    | '/org-admin/courses'
    | '/org-admin/departments'
    | '/org-admin/module-access'
    | '/org-admin/roles'
    | '/org-admin/users'
    | '/super-admin/activity'
    | '/super-admin/billing'
    | '/super-admin/dashboard'
    | '/super-admin/feature-registry'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/setup-guide'
    | '/super-admin/sites'
    | '/super-admin/toolkit'
    | '/org-admin'
    | '/courses/$courseId/assessment'
    | '/super-admin/organizations/$orgId'
    | '/super-admin/organizations/add'
    | '/super-admin/sites/$siteId'
    | '/super-admin/sites/add'
    | '/courses/$courseId/play/$lessonId'
    | '/org-admin/courses/$courseId/builder'
    | '/org-admin/courses/$courseId/preview'
    | '/super-admin/organizations/$orgId/edit'
    | '/super-admin/sites/$siteId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/authoring'
    | '/catalog'
    | '/certificates'
    | '/dashboard'
    | '/login'
    | '/messenger'
    | '/org-admin'
    | '/paths'
    | '/pending-registration'
    | '/profile'
    | '/reset-password'
    | '/super-admin'
    | '/users'
    | '/certificates/$certId'
    | '/courses/$courseId'
    | '/login/$orgSlug'
    | '/org-admin/activity'
    | '/org-admin/certificates'
    | '/org-admin/courses'
    | '/org-admin/departments'
    | '/org-admin/module-access'
    | '/org-admin/roles'
    | '/org-admin/users'
    | '/super-admin/activity'
    | '/super-admin/billing'
    | '/super-admin/dashboard'
    | '/super-admin/feature-registry'
    | '/super-admin/organizations'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/setup-guide'
    | '/super-admin/sites'
    | '/super-admin/toolkit'
    | '/org-admin/'
    | '/courses/$courseId/assessment'
    | '/super-admin/organizations_/$orgId'
    | '/super-admin/organizations_/add'
    | '/super-admin/sites_/$siteId'
    | '/super-admin/sites_/add'
    | '/courses/$courseId/play/$lessonId'
    | '/org-admin/courses/$courseId/builder'
    | '/org-admin/courses/$courseId/preview'
    | '/super-admin/organizations_/$orgId_/edit'
    | '/super-admin/sites_/$siteId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AuthoringRoute: typeof AuthoringRoute
  CatalogRoute: typeof CatalogRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRouteWithChildren
  MessengerRoute: typeof MessengerRoute
  OrgAdminRoute: typeof OrgAdminRouteWithChildren
  PathsRoute: typeof PathsRoute
  PendingRegistrationRoute: typeof PendingRegistrationRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  UsersRoute: typeof UsersRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-registration': {
      id: '/pending-registration'
      path: '/pending-registration'
      fullPath: '/pending-registration'
      preLoaderRoute: typeof PendingRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-admin': {
      id: '/org-admin'
      path: '/org-admin'
      fullPath: '/org-admin'
      preLoaderRoute: typeof OrgAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messenger': {
      id: '/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof MessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authoring': {
      id: '/authoring'
      path: '/authoring'
      fullPath: '/authoring'
      preLoaderRoute: typeof AuthoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-admin/': {
      id: '/org-admin/'
      path: '/'
      fullPath: '/org-admin/'
      preLoaderRoute: typeof OrgAdminIndexRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/super-admin/toolkit': {
      id: '/super-admin/toolkit'
      path: '/toolkit'
      fullPath: '/super-admin/toolkit'
      preLoaderRoute: typeof SuperAdminToolkitRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/sites': {
      id: '/super-admin/sites'
      path: '/sites'
      fullPath: '/super-admin/sites'
      preLoaderRoute: typeof SuperAdminSitesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/setup-guide': {
      id: '/super-admin/setup-guide'
      path: '/setup-guide'
      fullPath: '/super-admin/setup-guide'
      preLoaderRoute: typeof SuperAdminSetupGuideRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/plans': {
      id: '/super-admin/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminPlansRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations': {
      id: '/super-admin/organizations'
      path: '/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof SuperAdminOrganizationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/feature-registry': {
      id: '/super-admin/feature-registry'
      path: '/feature-registry'
      fullPath: '/super-admin/feature-registry'
      preLoaderRoute: typeof SuperAdminFeatureRegistryRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/billing': {
      id: '/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof SuperAdminBillingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/activity': {
      id: '/super-admin/activity'
      path: '/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperAdminActivityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/org-admin/users': {
      id: '/org-admin/users'
      path: '/users'
      fullPath: '/org-admin/users'
      preLoaderRoute: typeof OrgAdminUsersRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/roles': {
      id: '/org-admin/roles'
      path: '/roles'
      fullPath: '/org-admin/roles'
      preLoaderRoute: typeof OrgAdminRolesRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/module-access': {
      id: '/org-admin/module-access'
      path: '/module-access'
      fullPath: '/org-admin/module-access'
      preLoaderRoute: typeof OrgAdminModuleAccessRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/departments': {
      id: '/org-admin/departments'
      path: '/departments'
      fullPath: '/org-admin/departments'
      preLoaderRoute: typeof OrgAdminDepartmentsRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/courses': {
      id: '/org-admin/courses'
      path: '/courses'
      fullPath: '/org-admin/courses'
      preLoaderRoute: typeof OrgAdminCoursesRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/certificates': {
      id: '/org-admin/certificates'
      path: '/certificates'
      fullPath: '/org-admin/certificates'
      preLoaderRoute: typeof OrgAdminCertificatesRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/activity': {
      id: '/org-admin/activity'
      path: '/activity'
      fullPath: '/org-admin/activity'
      preLoaderRoute: typeof OrgAdminActivityRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/login/$orgSlug': {
      id: '/login/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/login/$orgSlug'
      preLoaderRoute: typeof LoginOrgSlugRouteImport
      parentRoute: typeof LoginRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certId': {
      id: '/certificates/$certId'
      path: '/$certId'
      fullPath: '/certificates/$certId'
      preLoaderRoute: typeof CertificatesCertIdRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/super-admin/sites_/add': {
      id: '/super-admin/sites_/add'
      path: '/sites/add'
      fullPath: '/super-admin/sites/add'
      preLoaderRoute: typeof SuperAdminSitesAddRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/sites_/$siteId': {
      id: '/super-admin/sites_/$siteId'
      path: '/sites/$siteId'
      fullPath: '/super-admin/sites/$siteId'
      preLoaderRoute: typeof SuperAdminSitesSiteIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations_/add': {
      id: '/super-admin/organizations_/add'
      path: '/organizations/add'
      fullPath: '/super-admin/organizations/add'
      preLoaderRoute: typeof SuperAdminOrganizationsAddRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations_/$orgId': {
      id: '/super-admin/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/super-admin/organizations/$orgId'
      preLoaderRoute: typeof SuperAdminOrganizationsOrgIdRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/courses/$courseId/assessment': {
      id: '/courses/$courseId/assessment'
      path: '/assessment'
      fullPath: '/courses/$courseId/assessment'
      preLoaderRoute: typeof CoursesCourseIdAssessmentRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/super-admin/sites_/$siteId_/edit': {
      id: '/super-admin/sites_/$siteId_/edit'
      path: '/sites/$siteId/edit'
      fullPath: '/super-admin/sites/$siteId/edit'
      preLoaderRoute: typeof SuperAdminSitesSiteIdEditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations_/$orgId_/edit': {
      id: '/super-admin/organizations_/$orgId_/edit'
      path: '/organizations/$orgId/edit'
      fullPath: '/super-admin/organizations/$orgId/edit'
      preLoaderRoute: typeof SuperAdminOrganizationsOrgIdEditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/org-admin/courses/$courseId/preview': {
      id: '/org-admin/courses/$courseId/preview'
      path: '/$courseId/preview'
      fullPath: '/org-admin/courses/$courseId/preview'
      preLoaderRoute: typeof OrgAdminCoursesCourseIdPreviewRouteImport
      parentRoute: typeof OrgAdminCoursesRoute
    }
    '/org-admin/courses/$courseId/builder': {
      id: '/org-admin/courses/$courseId/builder'
      path: '/$courseId/builder'
      fullPath: '/org-admin/courses/$courseId/builder'
      preLoaderRoute: typeof OrgAdminCoursesCourseIdBuilderRouteImport
      parentRoute: typeof OrgAdminCoursesRoute
    }
    '/courses/$courseId/play/$lessonId': {
      id: '/courses/$courseId/play/$lessonId'
      path: '/play/$lessonId'
      fullPath: '/courses/$courseId/play/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdPlayLessonIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CertificatesRouteChildren {
  CertificatesCertIdRoute: typeof CertificatesCertIdRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesCertIdRoute: CertificatesCertIdRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface LoginRouteChildren {
  LoginOrgSlugRoute: typeof LoginOrgSlugRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginOrgSlugRoute: LoginOrgSlugRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface OrgAdminCoursesRouteChildren {
  OrgAdminCoursesCourseIdBuilderRoute: typeof OrgAdminCoursesCourseIdBuilderRoute
  OrgAdminCoursesCourseIdPreviewRoute: typeof OrgAdminCoursesCourseIdPreviewRoute
}

const OrgAdminCoursesRouteChildren: OrgAdminCoursesRouteChildren = {
  OrgAdminCoursesCourseIdBuilderRoute: OrgAdminCoursesCourseIdBuilderRoute,
  OrgAdminCoursesCourseIdPreviewRoute: OrgAdminCoursesCourseIdPreviewRoute,
}

const OrgAdminCoursesRouteWithChildren = OrgAdminCoursesRoute._addFileChildren(
  OrgAdminCoursesRouteChildren,
)

interface OrgAdminRouteChildren {
  OrgAdminActivityRoute: typeof OrgAdminActivityRoute
  OrgAdminCertificatesRoute: typeof OrgAdminCertificatesRoute
  OrgAdminCoursesRoute: typeof OrgAdminCoursesRouteWithChildren
  OrgAdminDepartmentsRoute: typeof OrgAdminDepartmentsRoute
  OrgAdminModuleAccessRoute: typeof OrgAdminModuleAccessRoute
  OrgAdminRolesRoute: typeof OrgAdminRolesRoute
  OrgAdminUsersRoute: typeof OrgAdminUsersRoute
  OrgAdminIndexRoute: typeof OrgAdminIndexRoute
}

const OrgAdminRouteChildren: OrgAdminRouteChildren = {
  OrgAdminActivityRoute: OrgAdminActivityRoute,
  OrgAdminCertificatesRoute: OrgAdminCertificatesRoute,
  OrgAdminCoursesRoute: OrgAdminCoursesRouteWithChildren,
  OrgAdminDepartmentsRoute: OrgAdminDepartmentsRoute,
  OrgAdminModuleAccessRoute: OrgAdminModuleAccessRoute,
  OrgAdminRolesRoute: OrgAdminRolesRoute,
  OrgAdminUsersRoute: OrgAdminUsersRoute,
  OrgAdminIndexRoute: OrgAdminIndexRoute,
}

const OrgAdminRouteWithChildren = OrgAdminRoute._addFileChildren(
  OrgAdminRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminActivityRoute: typeof SuperAdminActivityRoute
  SuperAdminBillingRoute: typeof SuperAdminBillingRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminFeatureRegistryRoute: typeof SuperAdminFeatureRegistryRoute
  SuperAdminOrganizationsRoute: typeof SuperAdminOrganizationsRoute
  SuperAdminPlansRoute: typeof SuperAdminPlansRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSetupGuideRoute: typeof SuperAdminSetupGuideRoute
  SuperAdminSitesRoute: typeof SuperAdminSitesRoute
  SuperAdminToolkitRoute: typeof SuperAdminToolkitRoute
  SuperAdminOrganizationsOrgIdRoute: typeof SuperAdminOrganizationsOrgIdRoute
  SuperAdminOrganizationsAddRoute: typeof SuperAdminOrganizationsAddRoute
  SuperAdminSitesSiteIdRoute: typeof SuperAdminSitesSiteIdRoute
  SuperAdminSitesAddRoute: typeof SuperAdminSitesAddRoute
  SuperAdminOrganizationsOrgIdEditRoute: typeof SuperAdminOrganizationsOrgIdEditRoute
  SuperAdminSitesSiteIdEditRoute: typeof SuperAdminSitesSiteIdEditRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminActivityRoute: SuperAdminActivityRoute,
  SuperAdminBillingRoute: SuperAdminBillingRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminFeatureRegistryRoute: SuperAdminFeatureRegistryRoute,
  SuperAdminOrganizationsRoute: SuperAdminOrganizationsRoute,
  SuperAdminPlansRoute: SuperAdminPlansRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSetupGuideRoute: SuperAdminSetupGuideRoute,
  SuperAdminSitesRoute: SuperAdminSitesRoute,
  SuperAdminToolkitRoute: SuperAdminToolkitRoute,
  SuperAdminOrganizationsOrgIdRoute: SuperAdminOrganizationsOrgIdRoute,
  SuperAdminOrganizationsAddRoute: SuperAdminOrganizationsAddRoute,
  SuperAdminSitesSiteIdRoute: SuperAdminSitesSiteIdRoute,
  SuperAdminSitesAddRoute: SuperAdminSitesAddRoute,
  SuperAdminOrganizationsOrgIdEditRoute: SuperAdminOrganizationsOrgIdEditRoute,
  SuperAdminSitesSiteIdEditRoute: SuperAdminSitesSiteIdEditRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdAssessmentRoute: typeof CoursesCourseIdAssessmentRoute
  CoursesCourseIdPlayLessonIdRoute: typeof CoursesCourseIdPlayLessonIdRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdAssessmentRoute: CoursesCourseIdAssessmentRoute,
  CoursesCourseIdPlayLessonIdRoute: CoursesCourseIdPlayLessonIdRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  AuthoringRoute: AuthoringRoute,
  CatalogRoute: CatalogRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRouteWithChildren,
  MessengerRoute: MessengerRoute,
  OrgAdminRoute: OrgAdminRouteWithChildren,
  PathsRoute: PathsRoute,
  PendingRegistrationRoute: PendingRegistrationRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  UsersRoute: UsersRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
